---
title: "Rscripts"
author: "Lemeap"
date: '2021 2 06 '
output: html_document
editor_options: 
  chunk_output_type: console
---

#R버전 확인 작업
```{r}

#install.packages("installr")
library(installr)
install.R()
version
```

#기본적인 패키지 모듈 설치
```{r setup, include=FALSE}
#0. Set operating environment of this code
install.packages(c('openxlsx','nlstools','Metrics','scales','digitize','tidyverse','DBI','odbc','RPostgreSQL', 'extrafont'))
#1. Library source files
library(openxlsx)
library(nlstools)
library(tidyverse)
library(Metrics)
library(digitize)
library(ggplot2)
library(DBI)
library(odbc)
library(RPostgreSQL)
library(extrafont)

# Default fonts setup
windowsFonts(
  Arial   = windowsFont("Arial"),
  Calibri = windowsFont("Calibri"),
  Cambria = windowsFont("Cambria"),
  Times = windowsFont("Times New Roman")
  
)
font_import()
#loadfonts(device="win")
fonts()
```

```{r}
# PostgreSQL set
require("RPostgreSQL")
con = dbConnect(dbDriver("PostgreSQL"), dbname = "Research", host="localhost", port=5432, user="postgres", password="1234")
dbListTables(con)

# df
df = dbGetQuery(con, "SELECT T1.*, T2.pe, T2.re, T2.we, T2.bd, T2.bo, T2.fr, T2.ca, T2.pr, T2.p, T2.pcrit, T2.rhof, T2.rhov, T2.muf, T2.muv
                , T2.kf, T2.kv, T2.sigma, T2.dtin, T2.lam,T2.cpf, T2.cpv, T2.tsat, T2.v
                FROM chf_calid_4deng_tb T1
                INNER JOIN chf_prop_tb T2
                ON T1.index = cast(T2.run_id as bigint)
                AND T2.p BETWEEN 100 AND 100
                --AND T2.xe > 0.1;")

df1 = dbGetQuery(con, "SELECT T1.xt_park, T1.q, T1.xt_cal, T1.g, T1.q_cal, T2.pe, T2.re, T2.we, T2.bd, T2.bo, T2.fr, T2.ca, T2.pr, T2.p, T2.pcrit, T2.rhof, T2.rhov, T2.muf, T2.muv, T1.dh, T1.lh, T1.xi, T2.kf, T2.kv, T2.sigma, T2.dtin, T2.lam,T2.cpf, T2.cpv, T2.tsat, T2.v
                FROM chf_osv_sz_alg_gs_deng_tb T1
                INNER JOIN chf_prop_tb T2
                ON T1.index = cast(T2.index as bigint)
                AND T2.source LIKE 'D.H. Lee'
                ")


# Deng thesis에 나온 논문 결과를 비교하기 위한 데이터 추출
#조건: Lee data
#
#P: 69 bar, D= 9.25 - 11.17 mm, L = 0.86 - 3.66 m, G = 1961 - 4173 kg/m2s, Xin = -0.26 - -0.008, Xe = 0 - 0.47


                
#--AND T1.xt_cal between 0 and 1
#                --AND T2.st_cal < 1
```

```{r}
# 회귀분석으로 새로운 모델 만들기*((muf-muv)/(muf+muv))^e*(lh/dh)^b(cpf-cpv)/(cpf+cpv))^c
F1=formula(df$q ~ (a/sqrt(df$dh))*exp(-b*sqrt(df$g*df$xt_cal*(1+df$xt_cal^2)^3))) #*((kf-kv)/(kf+kv))^c *((rhof-rhov)/(rhof+rhov))^d*((muf-muv)/(muf+muv))^e)
Corl1=nls(F1, start = list(a=1, b=0.1), control = list(maxiter = 50000),data = df)
summary(Corl1)

pairs(bo ~ re + we + bo + xt_cal + pr + bd + fr , data= df)

coef(Corl1)[1]

```

```{r}

df[,'q_cal_new'] = (coef(Corl1)[1]/sqrt(df$dh))*exp(-coef(Corl1)[2]*sqrt(df$g*df$xt_cal*(1+df$xt_cal^2)^3))
df[,'reduce_p'] = df$p/df$pcrit

```

```{r}
fun.1 = function(x) (y=x)

ggplot(data=df, aes(x=q_cal_new, y=q)) +
  geom_point(aes(colour = bo)) + scale_colour_gradient(low = "blue", high = "red") +
  stat_smooth(method="nls", formula = y ~ x ) +
  #scale_shape_manual(values=rep(c(1:18,65:90))) +
  #scale_colour_manual(values = c("Red","Black","Blue")) +
  labs(y=expression(paste(italic("Measured Critical Heat Flux, qCHF_EXP [MW/m3] "))), x=expression(paste(italic("Calculated Critical Heat Flux, qCHF_CAL [MW/m3] ")))) +
  theme_bw(base_family = "Times") +
  theme(text=element_text(size=9.5)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor=element_blank(),
        #legend.justification =c(0,0.95), 
        #legend.position = c(0.05,0.95),
        #legend.background=element_rect(fill="white", size=0.5, linetype="solid", colour = "black"),
        #legend.title=element_blank(),
        #legend.key.height=unit(0.05, unit="cm"),
        #legend.key.width=unit(0.15, unit="cm"),
        #legend.direction = "horizontal", 
        #legend.key.size = unit(0.5,"cm"),
        #legend.text=element_text(size=6), 
        axis.title.x = element_text(vjust=2),
        axis.title.y=element_text(vjust=-1.5)) +
  scale_x_continuous(trans= "identity", limits = c(0,30)) +
  scale_y_continuous(trans= "identity", limits = c(0,30)) +
  stat_function(fun = fun.1, linetype="solid", colour="black", size =0.3) + #xlim=c(0.0004,0.12) 
  stat_function(fun = function(x) y=0.75*x, linetype="solid", colour="black", size =0.3) + #xlim=c(0.0004,0.12)
  stat_function(fun = function(x) y=1.25*x, linetype="solid", colour="black", size =0.3) #xlim=c(0.0004,0.12)
  scale_x_continuous(
   trans = "log10") +
   #limits = c(0.001, 1000000)) +
   #breaks = c(0.005, 0.01)) +
  scale_y_continuous(
   #limits = c(0.0001, 150),
   #breaks = c(0.0025, 0.001, 0.01, 0.02, 0.03),
   trans = "log10") +
  annotation_logticks(outside =FALSE, short = unit(0.1, "cm"), mid = unit(0.2, "cm"), base = 10, scaled = TRUE)
  #ggsave("Newcorrelation_over_We200.png", width = 10, height= 9, units = "cm", dpi=1200)
```

```{r}
#g^0.65*(xt_cal-xi)^0.62*(lh/dh)^-0.77*(p/pcrit)^-0.148
#*xt_cal^-1.2*(lh/dh)^0.31*(rhof-rhov)/(rhof+rhov)
#*(lh/dh)^-0.33*(muf/muv)^-1*(kf/kv)^-0.25*(rhof/rhov)^0.35
#(sigma/(v^2*rhof*dh))^0.5
ggplot(data=df, aes(x=g*(dh/lh)*exp(xt_cal), y=q)) +
  geom_point(aes(colour = pr)) + scale_colour_gradient(low = "blue", high = "red") +
  stat_smooth(method="nls", formula = y ~ x ) +
  #scale_shape_manual(values=rep(c(1:18,65:90))) +
  #scale_colour_manual(values = c("Red","Black","Blue")) +
  labs(y=expression(paste(italic("Critical Heat Flux, qCHF [MW/m3] "))), x=expression(paste(italic("GXt")))) +
  theme_bw(base_family = "Times") +
  theme(text=element_text(size=9.5)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor=element_blank(),
        #legend.justification =c(0,0.95), 
        #legend.position = c(0.05,0.95),
        #legend.background=element_rect(fill="white", size=0.5, linetype="solid", colour = "black"),
        #legend.title=element_blank(),
        #legend.key.height=unit(0.05, unit="cm"),
        #legend.key.width=unit(0.15, unit="cm"),
        #legend.direction = "horizontal", 
        #legend.key.size = unit(0.5,"cm"),
        #legend.text=element_text(size=6), 
        axis.title.x = element_text(vjust=2),
        axis.title.y=element_text(vjust=-1.5)) +
  scale_x_continuous(
   trans = "log10") +
   #limits = c(0.001, 1000000)) +
   #breaks = c(0.005, 0.01)) +
  scale_y_continuous(
   #limits = c(0.0001, 150),
   #breaks = c(0.0025, 0.001, 0.01, 0.02, 0.03),
   trans = "log10") +
  annotation_logticks(outside =FALSE, short = unit(0.1, "cm"), mid = unit(0.2, "cm"), base = 10, scaled = TRUE)
  #ggsave("Newcorrelation_over_We200.png", width = 10, height= 9, units = "cm", dpi=1200)
  
ggplot(data=df1, aes(x=sqrt(g*xt_cal*(1+xt_cal^2)^3), y=q*sqrt(dh))) +
  geom_point(aes(colour = pr)) + scale_colour_gradient(low = "blue", high = "red") +
labs(y=expression(paste(italic("Critical Heat Flux, qCHF [MW/m3] "))), x=expression(paste(italic("GXt")))) +
  theme_bw(base_family = "Times") +
  theme(text=element_text(size=9.5)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor=element_blank(),
        #legend.justification =c(0,0.95), 
        #legend.position = c(0.05,0.95),
        #legend.background=element_rect(fill="white", size=0.5, linetype="solid", colour = "black"),
        #legend.title=element_blank(),
        #legend.key.height=unit(0.05, unit="cm"),
        #legend.key.width=unit(0.15, unit="cm"),
        #legend.direction = "horizontal", 
        #legend.key.size = unit(0.5,"cm"),
        #legend.text=element_text(size=6), 
        axis.title.x = element_text(vjust=2),
        axis.title.y=element_text(vjust=-1.5)) +
  scale_x_continuous(trans= "identity", limits = c(0,40)) +
  scale_y_continuous(trans= "identity", limits = c(0,0.6)) 

```



실험 조건 범위를 그리기 위한 그래프
```{r}
reg_db$pntile=ntile(reg_db$p, 10)
summary(reg_db) 
hist(reg_db$p, breaks=20)

# pressure histogram
ggplot(data=df,aes(x=p)) +
  geom_histogram(binwidth=18, fill = "white", colour = "black") +
  theme_bw(base_family = "Times") +
  theme(text=element_text(size=9.5)) +
  theme(panel.grid.major = element_blank(), panel.grid.minor=element_blank(), legend.justification =c(0,0.05), legend.position = c(0.45,0.75),
        legend.background=element_rect(fill="white", size=0.5, linetype="solid", colour = "black"), legend.title=element_blank(),
        legend.key.height=unit(0.25, unit="cm"), legend.key.width=unit(0.15, unit="cm"), legend.direction = "horizontal", 
        legend.key.size = unit(0.5,"cm"), legend.text=element_text(size=6), axis.title.x = element_text(vjust=2)) +
  coord_trans(ylim = c(0,2500)) +
  labs(y=expression(paste(italic("Number of data "))), x=expression(paste(italic("Pressure  "), italic(" [bar]"))))
  #ggsave("Fig. 99. no. of data vs. pressure.png", height = 6.5, width = 8, unit = "cm", dpi = 1200)
```

